### PR TITLE
fix ExpressionChangedAfterItHasBeenCheckedError

### LINKED ISSUE #661: A error occur in local debugging env talking component.
## What do you suggest us to do?

image

## Additional context

Nothing.

### PR DESCRIPTION
**Pull request by xxyzz**
close #661

### CODE REVIEW

**Review by hv0905 — APPROVED** [review]

File: src/app/Controllers/talking.component.ts [hunk 1]
```diff
@@ -137,7 +136,7 @@ export class TalkingComponent implements OnDestroy, AfterViewInit {
         }
     }
 
-    public ngAfterViewInit(): void {
+    public ngOnInit(): void {
         const inputElement = <HTMLElement>document.querySelector('#chatInput');
```
Comment (hv0905) [inline src/app/Controllers/talking.component.ts:140]: Move L141-L149 to ngAfterViewInit to prevent null pointer.
in ngOnInit the dom element might not be inited immediately

**Review by hv0905 — CHANGES_REQUESTED** [review]
